import { getQuoteStatusLabel } from "~/lib/quote-status";

type PdfQuote = {
  quoteNumber: string;
  customerName?: string | null;
  customerEmail?: string | null;
  currency: string;
  status: string;
  originalTotal: number;
  quoteTotal: number;
  expiresAt?: string | Date | null;
  createdAt: string | Date;
  items: Array<{
    title: string;
    sku?: string | null;
    quantity: number;
    unitPrice: number;
    quotePrice: number;
  }>;
};

const money = (value: number, currency: string) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency || "USD",
  }).format(Number(value || 0));

const date = (value?: string | Date | null) =>
  value
    ? new Intl.DateTimeFormat("en-GB", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
      }).format(new Date(value))
    : "-";

const escapePdfText = (value: string) =>
  String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)")
    .replaceAll("\r", " ")
    .replaceAll("\n", " ");

function textLine(x: number, y: number, size: number, text: string) {
  return `BT /F1 ${size} Tf ${x} ${y} Td (${escapePdfText(text)}) Tj ET`;
}

export function createQuotePdf(quote: PdfQuote) {
  const lines: string[] = [];
  let y = 790;

  lines.push(textLine(42, y, 20, `Quote ${quote.quoteNumber}`));
  y -= 28;
  lines.push(textLine(42, y, 10, `Status: ${getQuoteStatusLabel(quote.status)}`));
  y -= 16;
  lines.push(textLine(42, y, 10, `Created: ${date(quote.createdAt)}`));
  y -= 16;
  lines.push(textLine(42, y, 10, `Expired: ${date(quote.expiresAt)}`));
  y -= 24;

  lines.push(textLine(42, y, 13, "Customer"));
  y -= 18;
  lines.push(textLine(42, y, 10, quote.customerName || "Guest customer"));
  y -= 14;
  lines.push(textLine(42, y, 10, quote.customerEmail || "No email"));
  y -= 28;

  lines.push(textLine(42, y, 13, "Quote items"));
  y -= 20;
  lines.push(textLine(42, y, 9, "Product"));
  lines.push(textLine(292, y, 9, "Qty"));
  lines.push(textLine(335, y, 9, "Price"));
  lines.push(textLine(415, y, 9, "Quote Price"));
  lines.push(textLine(505, y, 9, "Subtotal"));
  y -= 16;

  quote.items.slice(0, 18).forEach((item) => {
    const title =
      item.title.length > 42 ? `${item.title.slice(0, 39)}...` : item.title;
    const subtotal = Number(item.quotePrice || 0) * Number(item.quantity || 1);
    lines.push(textLine(42, y, 9, title));
    lines.push(textLine(292, y, 9, String(item.quantity)));
    lines.push(textLine(335, y, 9, money(item.unitPrice, quote.currency)));
    lines.push(textLine(415, y, 9, money(item.quotePrice, quote.currency)));
    lines.push(textLine(505, y, 9, money(subtotal, quote.currency)));
    y -= 15;
    if (item.sku) {
      lines.push(textLine(54, y, 8, item.sku));
      y -= 13;
    }
  });

  if (quote.items.length > 18) {
    lines.push(textLine(42, y, 9, `+ ${quote.items.length - 18} more items`));
    y -= 16;
  }

  y = Math.min(y - 20, 190);
  lines.push(textLine(335, y, 11, "Original total:"));
  lines.push(textLine(475, y, 11, money(quote.originalTotal, quote.currency)));
  y -= 22;
  lines.push(textLine(335, y, 14, "Quote total:"));
  lines.push(textLine(475, y, 14, money(quote.quoteTotal, quote.currency)));
  y -= 36;
  lines.push(
    textLine(
      42,
      y,
      8,
      "This PDF was generated by the Request for Quote app for record keeping.",
    ),
  );

  const content = lines.join("\n");
  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${Buffer.byteLength(content)} >> stream\n${content}\nendstream endobj`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}
