# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e40427a30e06018c3ba6e392de38d03"
application_url = "http://localhost:3000"
embedded = true
name = "Request a Quote"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,read_files,write_files,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback",
  "http://localhost:3000/api/auth/callback"
]

[app_proxy]
url = "/api/storefront"
prefix = "apps"
subpath = "request-a-quote"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact"
  ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
